### ISSUE TITLE
Feedback: Typical usage

### ISSUE THREAD

**Issue by vmasrani** [UBC-MDS/HAM_Python#35]
'Typical Usage' has lots of bugs - need to include:

```python
import numpy as np
```
and remove 'ham.' prefix (or change imports). Where are all the returned values?  The demo code should be something like:

```python
raw_data = np.matrix([[1, 2], [3, np.nan]])
df = impute_missing(raw_data, 'b', "CC", "NaN")
print df
```
Make sure to test the demo code!

**Comment by yllz** [comment]
5bb8fbaf440e3cd95ffddb42e855f1632ddc9359
